apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-volume
  labels:
    type: local
  annotations:
    description: "pgAdmin configuration data"
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/pgadmin