apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dso-assignment
commonLabels:
  app: postgres
  owner: viruskizz
images:
  - name: postgres
    newName: postgres
    newTag: 15-alpine
configMapGenerator:
  - name: postgresql-config
    envs:
      - .env
    behavior: merge
generatorOptions:
  disableNameSuffixHash: true
resources:
  - deployment.yaml
  - pv.yaml
  - pvc.yaml
  - configmap.yaml